name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  cloud_firestore: ^2.5.3
  animated_text_kit: ^4.2.1
  date_format: ^2.0.4
  shared_preferences: ^2.0.8


  flutter:
    sdk: flutter
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
